{{- if .Values.certificates.clusterIssuer.enabled -}}
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: fleetconfig-controller
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
spec:
  {{ .Values.certificates.clusterIssuer.spec | toYaml | indent 2 }}
{{- end -}}