name: E2E

on:
  workflow_call:
    inputs:
        repo:
          required: true
          type: string
        artifacts:
          required: false
          type: string
        ginkgoLabelFilter:
          required: false
          type: string

env:
  GO_REQUIRED_MIN_VERSION: ''

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install DevSpace
        uses: loft-sh/setup-devspace@main

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.4

      - name: Test E2E
        run: |
          cd ${{ inputs.repo }}
          LABEL_FILTER=${{ inputs.ginkgoLabelFilter }} make test-e2e

      - name: Upload Artifacts
        if: |
          (success() || failure()) && inputs.artifacts != ''
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v4
        with:
          name: e2e-artifacts
          path: ${{ inputs.artifacts }}
          if-no-files-found: ignore
          retention-days: 7